name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs: # test
  linux-x86_64-AVX512-cmake:
    name: TEST JOB2 Linux x86_64 AVX512 (cmake) on custom runner
    runs-on: faiss-aws-m7i.xlarge
    steps:
      - name: Checkout
        continue-on-error: true
        uses: actions/checkout@v4
